# -*- coding: utf-8 -*-
"""DL final project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18dTl5T-fdp-suddI0zdWVaY8BZdRKT0B
"""

!git clone https://github.com/peisuke/MomentumContrast.pytorch.git

!rm -rf lemniscate.pytorch

# Commented out IPython magic to ensure Python compatibility.
# %cd MomentumContrast.pytorch
!ls

!wget http://cs231n.stanford.edu/tiny-imagenet-200.zip

!ls
import tiny-imagenet-200

!python train.py

!python main.py tiny-imagenet-200 --arch resnet18 -j 32 --nce-k 4096 --nce-t 0.07 --lr 0.03 --nce-m 0.5 --low-dim 128 -b 256

python main.py tiny-imagenet-200 --arch resnet18 --resume input_model.pth.tar -e

